title: "MD Personal Trainer • Blog CNT"
description: "Treino, neurociência e saúde mental — base de conteúdo do canal CNT."
author: "Márcio Dowglas"
theme: jekyll-theme-minimal
show_downloads: false

url: "https://mbritodowglas-collab.github.io"
baseurl: "/mdpersonal"

whatsapp: 5592981037222

markdown: kramdown
highlighter: rouge
permalink: pretty
