title: "Márcio Dowglas Personal Trainer"
description: "Treinamento físico, neurociência e saúde mental — base de conteúdo do Blog CNT."
author: "Márcio Dowglas"
theme: jekyll-theme-minimal
show_downloads: false

url: "https://mbritodowglas-collab.github.io"
baseurl: "/mdpersonal"


whatsapp: 5592981037222

markdown: kramdown
highlighter: rouge
permalink: pretty

# Redes Sociais
social:
  instagram: "https://instagram.com/marciodowglasfitness"
  youtube: "https://youtube.com/@marciodowglas"
  tiktok: "https://tiktok.com/@marciodowglas"
  whatsapp: "https://wa.me/5592999999999"
  linkedin: "https://linkedin.com/in/marciodowglas"
