# ==========================================
# 🧠 CONFIGURAÇÃO GERAL DO SITE
# ==========================================
title: "Márcio Dowglas Personal Trainer"
description: "Treino, neurociência e saúde mental — artigos e conteúdos práticos baseados em ciência."
author: "Márcio Dowglas Souza de Brito"
email: "contato@mdpersonal.com"
url: "https://mbritodowglas-collab.github.io"
baseurl: "/mdpersonal"

# ==========================================
# 🧱 ESTRUTURA DE CONTEÚDO
# ==========================================
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ==========================================
# 🗂️ PASTAS PADRÃO
# ==========================================
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# ==========================================
# 🖼️ IMAGENS PADRÃO E CAMINHOS
# ==========================================
default_thumb: /assets/img/posts/default.jpg
default_af_thumb: /assets/img/af/default.jpg

# ==========================================
# 🔗 LINKS FIXOS DE AFILIADOS
# ==========================================
shopee_link: "https://shopee.com.br/"
fithouse_link: "https://www.fithouse.com.br/"

# ==========================================
# 📚 SEO E METADADOS
# ==========================================
social:
  instagram: "https://instagram.com/marciodowglasfitness"
  youtube: "https://youtube.com/@mdpersonal"
  site: "https://mbritodowglas-collab.github.io/mdpersonal"

# ==========================================
# ⚙️ BUILD
# ==========================================
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json

timezone: America/Manaus