title: "MD Personal • Blog CNT"
description: "Treino, neurociência e saúde mental — base de conteúdo do canal CNT."
theme: jekyll-theme-minimal
author: "Márcio Dowglas"
show_downloads: false

# adicionar CSS personalizado
include:
  - assets/css/style.css

# links de navegação
header_pages:
  - index.md
  - blog
  - about.md
