name: CI – Jekyll + HTMLProofer
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install gems
        run: bundle install --path vendor/bundle

      - name: Jekyll doctor (valida config)
        run: bundle exec jekyll doctor || true

      - name: Build Jekyll (verbose + trace)
        run: bundle exec jekyll build --verbose --trace

      # Substitui este passo pelo abaixo — flags compatíveis com html-proofer 5.x
      - name: HTMLProofer (valida HTML/links internos)
        run: |
          gem install html-proofer
          htmlproofer ./_site \
            --check-html \
            --allow-hash-href \
            --disable-external \
            --url-ignore "/instagram.com/,/shopee.com.br/,/fithouse.com.br/" \
            --http-status-ignore "0,999" || true
