name: CI – Jekyll + HTMLProofer

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll (verbose)
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace --verbose

      - name: HTMLProofer (valida HTML/links)
        run: |
          bundle exec htmlproofer ./_site \
            --check-html \
            --allow-missing-hrefs \
            --no-enforce-https \
            --url-ignore "/instagram.com/,/shopee.com.br/,/fithouse.com.br/" \
            --http-status-ignore "0,999"